Fixed Attestation link size to match other "buttons"
bitwarden/passwordless-server pull request #381
Opened 2024-02-01 20:35 UTC by jrmccannon

Added `flex` to wrapping `div` so that the button size matched others on the page.

Before:

After:

2024-02-02 11:19 UTC, jonashendrickx submitted a review, later dismissed

2024-02-02 12:34 UTC, abergs requested changes

2024-02-02 12:34 UTC, abergs commented on src/AdminConsole/Pages/App/Settings/Settings.cshtml
> +        <div class="flex">
I think we'd rather change the implementation of `.btn-primary` to use `display:inline-block`

2024-02-05 14:27 UTC, abergs approved these changes

2024-02-05 14:41 UTC, merged