Create CODEOWNERS
bitwarden/passwordless-server pull request #383
Opened 2024-02-02 07:01 UTC by jonashendrickx

2024-02-02 09:07 UTC, abergs requested changes
Please add description and reasoning for suggesting this change.

2024-02-02 09:13 UTC, abergs requested changes

2024-02-02 09:13 UTC, abergs commented on .github/CODEOWNERS
> +.github/workflows @bitwarden/dept-devops
Comment this out for now

2024-02-02 11:50 UTC, abergs reviewed
I think this looks fair now, but as I don't know anything about codeowners, maybe @Tyrrrz could confirm and approve

2024-02-02 14:17 UTC, Tyrrrz approved these changes
Looks fine in the final state

2024-02-02 14:23 UTC, jrmccannon commented
It puts all members of our team into the list of people who have to approve a PR for it to go in, but then the workflow addition allows devops to make changes to the workflow pipelines without bothering us. It is inline with the rest of the organization.

2024-02-02 14:23 UTC, jrmccannon approved these changes

2024-02-03 11:44 UTC, Tyrrrz commented
> but then the workflow addition allows devops to make changes to the workflow pipelines without bothering us.

That's not really how it works, they can already do that now. Instead, it will make it so all changes to the workflow will tag the devops team.

2024-02-03 15:02 UTC, merged